FROM fedora:latest

WORKDIR /app
COPY . /app

# these are usually on my systems
RUN mkdir -p /root/Documents/mock_results
RUN mkdir -p /root/.local/bin

RUN dnf install make pip fish vim git conky python3-click rsync -y
RUN pip install konsave
RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
