#!/bin/bash


set -e

get_remote() {
    case "$1" in
        "o")
            echo "origin"
            ;;
        "u")
            echo "upstream"
            ;;
        *)
            echo "$1"
            ;;
    esac
}


remote=$(get_remote "$@")
shift

if ! [ -z "$1" ]; then
    git fetch "$remote" "$@"
    exit 0
fi

git fetch "$remote" "$branch"
