source = ~/.config/hypr/config/hyprland/monitor.conf
source = ~/.config/hypr/config/hyprland/env.conf
source = ~/.config/hypr/config/hyprland/window.conf
source = ~/.config/hypr/config/hyprland/animation.conf
source = ~/.config/hypr/config/hyprland/key_bindings.conf
source = ~/.config/hypr/config/hyprland/decoration.conf
source = ~/.config/hypr/config/hyprland/input.conf
source = ~/.config/hypr/config/hyprland/layout.conf
source = ~/.config/hypr/config/hyprland/exec.conf


workspace = defaultName:1a, name:1a, default:true, monitor:desc:Dell Inc. DELL SE2723DS DMF4WP3

workspace = defaultName:1b, name:1b, default:true, monitor:desc:Samsung Electric Company S24F350 H4ZN900284

workspace = defaultName:1c, name:1c, default:true, monitor:desc:AU Optronics 0xD291
