---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/../../collections/requirements.yml

driver:
  name: podman

platforms:
  - name: vercajk-dotfiles-test
    image: registry.fedoraproject.org/fedora:latest
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      vercajk-dotfiles-test:
        target_user: testuser
        home_dir: /home/testuser

verifier:
  name: testinfra
  options:
    v: true
