---
- name: Install hyprland
  package:
    name: hyprland
    state: present

- name: Install packages needed for nice DE
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ hyprland_packages }}"

- name: Enable copr repo for hyprland packages
  community.general.copr:
    name: nikropmen/hyprland
    state: enabled

- name: Install packages that are not yet in fedora repo
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - hyprlock
