---
- name: Create folders in root of Documents
  become: true
  become_user: "{{ target_user }}"
  file:
    path: "{{ home_dir }}/Documents/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ docs_root_dirs }}"

- name: Create directories for git forges
  become: true
  become_user: "{{ target_user }}"
  file:
    path: "{{ home_dir }}/Documents/git/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ git_forges }}"

- name: Create rpm folder hierarchy inside Documents
  become: true
  become_user: "{{ target_user }}"
  file:
    path: "{{ home_dir }}/Documents/rpm/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ rpm_docs_dirs }}"

- name: Create directories for compiling software from source
  become: true
  become_user: "{{ target_user }}"
  file:
    path: "{{ home_dir }}/Documents/src/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - local
    - global
