---
- name: Play the dotfiles role on localhost
  hosts: localhost
  become: true

  vars_files:
    - group_vars/all

  tasks:
    - name: Apply dotfiles role for each target user
      include_role:
        name: dotfiles
      loop: "{{ target_users }}"
      loop_control:
        loop_var: target_user
      vars:
        home_dir: "/home/{{ target_user }}"
