name: Ansible - Lint

on:
  push:
    paths: [ansible/**]
    branches: [main]
  pull_request:
    paths: [ansible/**]

jobs:
  lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ansible-core
        run: pip install ansible-core

      - name: Install collections
        run: ansible-galaxy collection install -r ansible/collections/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
